# -*- coding: utf-8 -*-
"""Kopia av final_project_example.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YYozvCZVsdogRp5iXCgpSIRbl1dMru0B

# The "AlphaFold vs. Reality" Test

### _Pick 20 proteins. Download the experimental crystal structure from PDB and the predicted structure from the AlphaFold database. Calculate the local RMSD per residue. Identify which regions AlphaFold failed to predict accurately (e.g., disordered loops)._

## Main steps (what to run)

1. **Dependencies**: run the first setup/import cell to install/check packages.
2. **Project setup**: run the folders + plotting-defaults setup cell.
3. **Phase A — Data extraction**: choose/edit the `PDB_IDS` list (aim for ~20) and run the Phase A pipeline (download → parse → clean → map chain to UniProt → download AlphaFold).
4. **Phase B — Sequence analysis**: run the identity-matrix cells (they save CSV + heatmaps).
5. **Phase C — Structural analysis**: run the superposition + per-residue deviation cells (they save per-protein CSV + plots) and the “bad regions” summary.
6. **Phase D — Ligand contacts**: run the ligand-contact analysis if ligands exist in your structures.

Outputs are written under `generated/` folder.

<div style="text-align: center; font-size: 24px; font-weight: bold; border-top: 5px solid green; border-bottom: 2px solid green; padding: 10px;">
   1. Check and install dependencies
</div>
"""

# Setup: install (if needed) + all imports (run once)
from __future__ import annotations

import importlib.util
import subprocess
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

def ensure_package(pip_name: str, import_name: str | None = None) -> None:
    """Ensure a package is installed (via pip) so imports succeed."""
    name = import_name or pip_name
    if importlib.util.find_spec(name) is not None:
        return
    print(f"Installing: {pip_name}")
    subprocess.check_call([sys.executable, "-m", "pip", "install", pip_name])

# Core dependencies used throughout this notebook
ensure_package("biopython", "Bio")
ensure_package("pandas")
ensure_package("numpy")
ensure_package("matplotlib")
ensure_package("requests")

# Third-party imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
from IPython.display import display
from Bio import ExPASy, SwissProt
from Bio.Align import PairwiseAligner
from Bio.PDB import MMCIFParser, NeighborSearch, PDBParser, Superimposer, is_aa
from Bio.SeqUtils import seq1

# Optional dependency: PyMOL (only needed for the overlay section)
sys.path.append('/usr/lib/python3/dist-packages')
try:
    !apt-get update
    !apt-get install -y pymol
    import pymol  # type: ignore
    pymol.pymol_argv = ['pymol', '-qc']
    pymol.finish_launching()
    from pymol import cmd  # type: ignore
    HAS_PYMOL = True
    print("Dependencies + imports OK")
except Exception as e:
    pymol = None
    cmd = None
    HAS_PYMOL = False
    print(f"No pymol. The exact error is: {e}")

# Phase 0: Setup (folders + plot defaults)

# Make plots look decent by default
plt.rcParams.update({"figure.dpi": 120, "savefig.dpi": 180})

PROJECT_DIR = Path.cwd()
GENERATED_DIR = PROJECT_DIR / "generated"
FIGURES_DIR = GENERATED_DIR / "figures"
DOWNLOADS_DIR = GENERATED_DIR / "downloads"
RESULTS_DIR = GENERATED_DIR / "results"

for d in [GENERATED_DIR, FIGURES_DIR, DOWNLOADS_DIR, RESULTS_DIR]:
    d.mkdir(parents=True, exist_ok=True)

print("Project folders ready:")
print("-", GENERATED_DIR)
print("-", FIGURES_DIR)

"""<div style="text-align: center; font-size: 24px; font-weight: bold; border-top: 5px solid green; border-bottom: 2px solid green; padding: 10px;">
   3. Phase A: Data Extraction
</div>

Input: A list of PDB IDs or a search query (e.g., "organism: Homo sapiens AND ligand: ATP"). <br>
Tools: Bio.PDB module to parse .pdb or .mmcif files. <br>
Task: Clean the data. Remove water molecules; handle missing residues; separate chains.
"""

# Phase A: Download + clean + extract chains (simple functions)

@dataclass(frozen=True)
class ProteinEntry:
    """A single experimental chain mapped to a UniProt accession."""

    pdb_id: str
    chain_id: str
    uniprot_id: str


def fetch_uniprot_sequence(uniprot_id: str) -> str:
    """Fetch the canonical UniProt sequence via SwissProt."""
    handle = ExPASy.get_sprot_raw(uniprot_id)
    record = SwissProt.read(handle)
    return record.sequence


def download_file(url: str, out_path: Path, timeout: int = 60) -> Path:
    """Download a URL to disk (skips if the file already exists)."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    if out_path.exists() and out_path.stat().st_size > 0:
        return out_path
    r = requests.get(url, timeout=timeout)
    r.raise_for_status()
    out_path.write_bytes(r.content)
    return out_path


def download_rcsb_mmcif(pdb_id: str) -> Path:
    """Download an RCSB mmCIF file for a PDB ID."""
    pdb_id = pdb_id.upper()
    url = f"https://files.rcsb.org/download/{pdb_id}.cif"
    out_path = DOWNLOADS_DIR / f"{pdb_id}.cif"
    return download_file(url, out_path)


def download_alphafold_pdb(uniprot_id: str) -> Path:
    """Download the latest AlphaFold model for a UniProt accession.

    Uses the AlphaFold API first (recommended), then falls back to common versioned filenames.
    Returns a local path (usually .pdb or .cif).
    """
    uniprot_id = uniprot_id.upper()

    # Reuse any already-downloaded model first (prefer PDB).
    already = (
        sorted(DOWNLOADS_DIR.glob(f"AF-{uniprot_id}-F1-model_v*.pdb"), reverse=True)
        + sorted(DOWNLOADS_DIR.glob(f"AF-{uniprot_id}-F1-model_v*.cif"), reverse=True)
        + [DOWNLOADS_DIR / f"AF-{uniprot_id}.pdb"]
    )
    for p in already:
        if p.exists() and p.stat().st_size > 0:
            return p

    api_url = f"https://alphafold.ebi.ac.uk/api/prediction/{uniprot_id}"
    last_err = None
    try:
        r = requests.get(api_url, timeout=30)
        r.raise_for_status()
        data = r.json()
        if isinstance(data, list) and len(data) > 0:
            rec = data[0]
            model_url = rec.get("pdbUrl") or rec.get("cifUrl") or rec.get("bcifUrl")
            if model_url:
                out_path = DOWNLOADS_DIR / Path(model_url).name
                return download_file(model_url, out_path)
    except Exception as e:
        last_err = e

    # Fallback: try a range of versions if the API is unavailable.
    versions = [f"v{i}" for i in range(6, 0, -1)]
    for v in versions:
        for ext in ("pdb", "cif"):
            url = f"https://alphafold.ebi.ac.uk/files/AF-{uniprot_id}-F1-model_{v}.{ext}"
            out_path = DOWNLOADS_DIR / f"AF-{uniprot_id}-F1-model_{v}.{ext}"
            try:
                return download_file(url, out_path)
            except Exception as e:
                last_err = e
                continue

    raise RuntimeError(
        f"Could not download AlphaFold model for {uniprot_id}. "
        f"Tried API ({api_url}) and common versioned filenames. Last error: {last_err}"
    )


def parse_structure(path: Path, structure_id: str):
    """Parse a mmCIF or PDB file into a Biopython Structure."""
    suffix = path.suffix.lower()
    if suffix == ".cif":
        parser = MMCIFParser(QUIET=True)
        return parser.get_structure(structure_id, str(path))
    if suffix == ".pdb":
        parser = PDBParser(QUIET=True)
        return parser.get_structure(structure_id, str(path))
    raise ValueError(f"Unsupported file type: {path}")


def get_chain(structure, chain_id: str):
    """Return a chain from the first model (raises a helpful error if missing)."""
    model = next(structure.get_models())
    try:
        return model[chain_id]
    except KeyError as e:
        available = [c.id for c in model.get_chains()]
        raise KeyError(f"Chain {chain_id} not found. Available: {available}") from e


def iter_standard_residues_with_ca(chain):
    """Yield standard amino-acid residues that have a CA atom."""
    for res in chain.get_residues():
        if is_aa(res, standard=True) and "CA" in res:
            yield res


def chain_sequence_and_residues(chain) -> Tuple[str, List]:
    """Return (sequence, residues_list) using standard AA residues with CA."""
    residues = list(iter_standard_residues_with_ca(chain))
    seq = "".join(seq1(r.get_resname()) for r in residues)
    return seq, residues


def align_index_pairs(seq_a: str, seq_b: str) -> List[Tuple[int, int]]:
    """Return list of (i, j) index pairs for aligned (non-gap) positions."""
    aligner = PairwiseAligner()
    aligner.mode = "global"
    aligner.match_score = 2
    aligner.mismatch_score = -1
    aligner.open_gap_score = -0.5
    aligner.extend_gap_score = -0.1
    aln = aligner.align(seq_a, seq_b)[0]
    pairs: List[Tuple[int, int]] = []
    # aln.aligned gives matching blocks in A and B
    blocks_a = aln.aligned[0]
    blocks_b = aln.aligned[1]
    for (a0, a1), (b0, b1) in zip(blocks_a, blocks_b):
        length = min(a1 - a0, b1 - b0)
        for k in range(length):
            pairs.append((a0 + k, b0 + k))
    return pairs


def aligned_identity(seq_a: str, seq_b: str) -> float:
    """Percent identity on aligned (non-gap) positions."""
    pairs = align_index_pairs(seq_a, seq_b)
    if not pairs:
        return 0.0
    matches = sum(1 for i, j in pairs if seq_a[i] == seq_b[j])
    return 100.0 * matches / len(pairs)


def superpose_on_ca(exp_chain, af_chain) -> Tuple[float, List[Dict]]:
    """Superpose AF chain onto experimental chain using aligned CA atoms.

    Returns (global_rmsd_A, per_residue_records) where per_residue_records includes
    CA distance after superposition for each aligned residue pair.
    """
    exp_seq, exp_res = chain_sequence_and_residues(exp_chain)
    af_seq, af_res = chain_sequence_and_residues(af_chain)
    pairs = align_index_pairs(exp_seq, af_seq)
    if len(pairs) < 10:
        raise RuntimeError(f"Too few aligned residues ({len(pairs)}). Check chain IDs / sequences.")

    exp_atoms = [exp_res[i]["CA"] for i, j in pairs]
    af_atoms = [af_res[j]["CA"] for i, j in pairs]

    sup = Superimposer()
    sup.set_atoms(exp_atoms, af_atoms)
    sup.apply(list(af_chain.get_atoms()))
    global_rmsd = float(sup.rms)

    records: List[Dict] = []
    for (i, j) in pairs:
        exp_ca = exp_res[i]["CA"].get_coord()
        af_ca = af_res[j]["CA"].get_coord()
        dist = float(np.linalg.norm(exp_ca - af_ca))
        records.append(
            {
                "exp_resseq": int(exp_res[i].id[1]),
                "exp_resname": exp_res[i].get_resname(),
                "af_resseq": int(af_res[j].id[1]),
                "af_resname": af_res[j].get_resname(),
                "ca_distance_A": dist,
            },
        )
    return global_rmsd, records


# The notebook will auto-resolve the correct UniProt accession for each PDB chain
# using RCSB (SIFTS-backed) cross-references, then download the AlphaFold model.

RCSB_GRAPHQL = "https://data.rcsb.org/graphql"
_RCSB_ENTITY_QUERY = """
query($id: String!) {
  entry(entry_id: $id) {
    polymer_entities {
      rcsb_id
      entity_poly { pdbx_strand_id }
      rcsb_polymer_entity_container_identifiers { uniprot_ids }
    }
  }
}
"""


def _rcsb_polymer_entities(pdb_id: str) -> List[Dict]:
    """Query RCSB GraphQL for polymer entities and UniProt cross-references."""
    r = requests.post(
        RCSB_GRAPHQL,
        json={"query": _RCSB_ENTITY_QUERY, "variables": {"id": pdb_id.upper()}},
        timeout=30,
    )
    r.raise_for_status()
    entry = (r.json().get("data") or {}).get("entry")
    if not entry:
        raise ValueError(f"RCSB returned no entry for PDB ID {pdb_id}")
    entities = entry.get("polymer_entities") or []
    out: List[Dict] = []
    for ent in entities:
        chains_raw = ((ent.get("entity_poly") or {}).get("pdbx_strand_id") or "").strip()
        chains = [c.strip() for c in chains_raw.split(",") if c.strip()]
        uniprot_ids = (
            (ent.get("rcsb_polymer_entity_container_identifiers") or {}).get("uniprot_ids")
            or []
        )
        out.append({"entity_id": ent.get("rcsb_id"), "chains": chains, "uniprot_ids": uniprot_ids})
    return out


def resolve_chain_and_uniprot(
    pdb_id: str, preferred_chain: str = "A", strict_chain: bool = False
 ) -> Tuple[str, str, List[str], str]:
    """Resolve a (chain_id, uniprot_id) for a PDB entry.

    - If preferred_chain exists, use it.
    - If it doesn't exist and strict_chain=False, pick the first protein chain that has a UniProt mapping.
    - If multiple UniProt IDs map to the same chain, we pick the first and record a note.
    """
    pdb_id = pdb_id.upper()
    preferred_chain = preferred_chain.strip()
    entities = _rcsb_polymer_entities(pdb_id)

    # 1) Preferred chain if present
    if preferred_chain:
        for ent in entities:
            if preferred_chain in ent["chains"]:
                unis = ent["uniprot_ids"]
                if not unis:
                    raise ValueError(f"{pdb_id} chain {preferred_chain}: found chain but no UniProt mapping in RCSB")
                note = ""
                if len(unis) > 1:
                    note = f"Multiple UniProt IDs for chain {preferred_chain}: {unis} (picked {unis[0]})"
                return preferred_chain, unis[0], unis, note

    if strict_chain:
        all_chains = sorted({c for e in entities for c in e["chains"]})
        raise ValueError(f"{pdb_id}: preferred chain {preferred_chain!r} not found. Available: {all_chains}")

    # 2) Fallback: first entity with a UniProt mapping
    for ent in entities:
        unis = ent["uniprot_ids"]
        if unis and ent["chains"]:
            chosen_chain = ent["chains"][0]
            note = f"Preferred chain {preferred_chain!r} not found; using chain {chosen_chain}"
            if len(unis) > 1:
                note += f" | Multiple UniProt IDs: {unis} (picked {unis[0]})"
            return chosen_chain, unis[0], unis, note

    raise ValueError(f"{pdb_id}: could not find any polymer entity with UniProt mapping")


def build_mapping_table(
    pdb_ids: List[str], preferred_chain: str = "A", strict_chain: bool = False
 ) -> pd.DataFrame:
    """Build a table mapping each PDB ID to a chosen chain and UniProt ID."""
    rows: List[Dict] = []
    for pdb_id in pdb_ids:
        chain_id, uniprot_id, unis, note = resolve_chain_and_uniprot(
            pdb_id, preferred_chain=preferred_chain, strict_chain=strict_chain
        )
        rows.append(
            {
                "pdb_id": pdb_id.upper(),
                "requested_chain": preferred_chain,
                "chosen_chain": chain_id,
                "uniprot_id": uniprot_id,
                "all_uniprot_ids": ",".join(unis),
                "note": note,
            },
        )
    return pd.DataFrame(rows)


def alphafold_latest_model_url(uniprot_id: str) -> str | None:
    """Return the latest AlphaFold model URL for a UniProt ID, or None if not available."""
    api_url = f"https://alphafold.ebi.ac.uk/api/prediction/{uniprot_id.upper()}"
    try:
        r = requests.get(api_url, timeout=20)
        if r.status_code == 404:
            return None
        r.raise_for_status()
        data = r.json()
        if isinstance(data, list) and len(data) > 0:
            rec = data[0]
            return rec.get("pdbUrl") or rec.get("cifUrl") or rec.get("bcifUrl")
    except Exception:
        return None
    return None

"""## Start the run:"""

# Phase A run: choose proteins, download files, parse, pick chains

# You only need to provide PDB IDs below.

# --- Edit these three lines only ---
DEFAULT_CHAIN_ID = "A"  # preference; set strict_chain=True below to force it
PDB_IDS = ["4WM6","1ZAK","1SYR","5XV5","1HG3","1P7G","4XIW","4APW","5MBA","1CKK","5B61","1B25","1BRS","4RX2","2XQ1","1LDM","7JQA","5BT8","1GRE","1QHT"]
STRICT_CHAIN = False  # True => fail if DEFAULT_CHAIN_ID does not exist in the PDB entry

# Build mapping table (PDB chain -> UniProt) and check AlphaFold availability
mapping_df = build_mapping_table(PDB_IDS, preferred_chain=DEFAULT_CHAIN_ID, strict_chain=STRICT_CHAIN)
mapping_df["alphafold_url"] = [alphafold_latest_model_url(u) for u in mapping_df["uniprot_id"]]
mapping_df["alphafold_available"] = mapping_df["alphafold_url"].notna()
display(mapping_df)

# By default, skip entries that don't have an AlphaFold model (otherwise Phase A will error).
SKIP_IF_NO_ALPHAFOLD = True
if SKIP_IF_NO_ALPHAFOLD:
    mapping_df = mapping_df[mapping_df["alphafold_available"]].reset_index(drop=True)
    print(f"Keeping {len(mapping_df)}/{len(PDB_IDS)} entries with AlphaFold models")

proteins: List[ProteinEntry] = [
    ProteinEntry(pdb_id=r.pdb_id, chain_id=r.chosen_chain, uniprot_id=r.uniprot_id)
    for r in mapping_df.itertuples(index=False)
 ]

phaseA_rows = []
for p in proteins:
    exp_path = download_rcsb_mmcif(p.pdb_id)
    try:
        af_path = download_alphafold_pdb(p.uniprot_id)
    except Exception as e:
        print(f"Skipping {p.pdb_id}:{p.chain_id} ({p.uniprot_id}) - AlphaFold download failed: {e}")
        continue

    exp_struct = parse_structure(exp_path, f"EXP_{p.pdb_id}")
    af_struct = parse_structure(af_path, f"AF_{p.uniprot_id}")

    exp_chain = get_chain(exp_struct, p.chain_id)
    # AlphaFold PDB usually has chain 'A'
    af_chain = get_chain(af_struct, "A")

    exp_seq, exp_res = chain_sequence_and_residues(exp_chain)
    af_seq, af_res = chain_sequence_and_residues(af_chain)

    phaseA_rows.append(
        {
            "pdb_id": p.pdb_id,
            "chain_id": p.chain_id,
            "uniprot_id": p.uniprot_id,
            "exp_file": str(exp_path),
            "af_file": str(af_path),
            "exp_len": len(exp_seq),
            "af_len": len(af_seq),
        }
    )
    print(f"{p.pdb_id} chain {p.chain_id}: exp_len={len(exp_seq)} | AF_len={len(af_seq)}")

phaseA_df = pd.DataFrame(phaseA_rows)
phaseA_df.to_csv(RESULTS_DIR / "phaseA_summary.csv", index=False)
phaseA_df

# Optional quick check: UniProt vs experimental chain sequence (Phase A sanity)

for p in proteins:
    exp_path = Path(phaseA_df.loc[0, "exp_file"])
    exp_struct = parse_structure(exp_path, f"EXP_{p.pdb_id}")
    exp_chain = get_chain(exp_struct, p.chain_id)
    exp_seq, _ = chain_sequence_and_residues(exp_chain)

    try:
        uni_seq = fetch_uniprot_sequence(p.uniprot_id)
        pid = aligned_identity(uni_seq, exp_seq)
        print(f"UniProt {p.uniprot_id} vs {p.pdb_id}:{p.chain_id} aligned identity: {pid:.1f}%")
    except Exception as e:
        print("UniProt fetch failed (network/ID mismatch). You can ignore this step.")
        print("Error:", e)

"""<div style="text-align: center; font-size: 24px; font-weight: bold; border-top: 5px solid green; border-bottom: 2px solid green; padding: 10px;">
   4. Phase B: Sequence Analysis
</div>

Extract the amino acid sequence from the 3D structure file (SEQRES vs. ATOM coordinates). <br>
Perform Multiple Sequence Alignment (MSA) using tools like Clustal or Muscle (called via Python wrapper).<br>
Output: A sequence identity matrix.
"""

# Phase B: Sequence analysis (pairwise identity matrices)

def compute_identity_matrix(labels: List[str], seqs: List[str]) -> pd.DataFrame:
    """Pairwise identity matrix using aligned-only identity (matches / aligned pairs)."""
    n = len(seqs)
    mat = np.zeros((n, n), dtype=float)
    for i in range(n):
        for j in range(n):
            mat[i, j] = aligned_identity(seqs[i], seqs[j])
    return pd.DataFrame(mat, index=labels, columns=labels)

def identity_over_maxlen_and_coverage_matrix(labels: List[str], seqs: List[str]) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """Return (identity_over_maxlen_pct, aligned_coverage_pct) matrices.

    - identity_over_maxlen_pct = matches / max(lenA, lenB) * 100
    - aligned_coverage_pct = aligned_pairs / max(lenA, lenB) * 100
    """
    n = len(seqs)
    id_over_maxlen = np.zeros((n, n), dtype=float)
    coverage = np.zeros((n, n), dtype=float)
    for i in range(n):
        for j in range(n):
            a, b = seqs[i], seqs[j]
            pairs = align_index_pairs(a, b)
            if not pairs:
                continue
            matches = sum(1 for ia, jb in pairs if a[ia] == b[jb])
            denom_maxlen = max(len(a), len(b))
            id_over_maxlen[i, j] = 100.0 * matches / denom_maxlen
            coverage[i, j] = 100.0 * len(pairs) / denom_maxlen
    return (
        pd.DataFrame(id_over_maxlen, index=labels, columns=labels),
        pd.DataFrame(coverage, index=labels, columns=labels),
    )

# Build sequences from Phase A files (experimental chains + AlphaFold chains)
exp_labels: List[str] = []
exp_seqs: List[str] = []
af_labels: List[str] = []
af_seqs: List[str] = []

for _, row in phaseA_df.iterrows():
    pdb_id = row["pdb_id"]
    chain_id = row["chain_id"]
    uniprot_id = row["uniprot_id"]

    exp_struct = parse_structure(Path(row["exp_file"]), f"EXP_{pdb_id}")
    af_struct = parse_structure(Path(row["af_file"]), f"AF_{uniprot_id}")

    exp_chain = get_chain(exp_struct, chain_id)
    af_chain = get_chain(af_struct, "A")

    exp_seq, _ = chain_sequence_and_residues(exp_chain)
    af_seq, _ = chain_sequence_and_residues(af_chain)

    exp_labels.append(f"{pdb_id}:{chain_id}")
    exp_seqs.append(exp_seq)
    af_labels.append(f"AF:{uniprot_id}")
    af_seqs.append(af_seq)

exp_id_df = compute_identity_matrix(exp_labels, exp_seqs)
af_id_df = compute_identity_matrix(af_labels, af_seqs)

exp_id_df.to_csv(FIGURES_DIR / "sequence_identity_matrix_experimental.csv")
af_id_df.to_csv(FIGURES_DIR / "sequence_identity_matrix_alphafold.csv")

display(exp_id_df.head(2))
print("Saved:")
print("-", FIGURES_DIR / "sequence_identity_matrix_experimental.csv")
print("-", FIGURES_DIR / "sequence_identity_matrix_alphafold.csv")

# Identity diagnostics (kept minimal)
def _offdiag_vals(df: pd.DataFrame) -> np.ndarray:
    """Return the off-diagonal values of a square matrix DataFrame as a 1D array."""
    v = df.values.astype(float)
    mask = ~np.eye(v.shape[0], dtype=bool)
    return v[mask]

def _print_stats(name: str, df: pd.DataFrame) -> None:
    """Print min/median/mean/max for off-diagonal identity values."""
    vals = _offdiag_vals(df)
    if len(vals) == 0:
        print(f"{name}: no off-diagonal values")
        return
    print(
        f"{name}: off-diagonal min/median/mean/max = "
        f"{np.min(vals):.1f} / {np.median(vals):.1f} / {np.mean(vals):.1f} / {np.max(vals):.1f}"
    )

print("=== Identity sanity checks ===")
print("Note: exp_id_df / af_id_df are aligned-only identity (matches / aligned pairs).")
print("This can look artificially high if only a short region aligns.")

# Duplicate-sequence check (simple)
for title, labels, seqs in [("Experimental", exp_labels, exp_seqs), ("AlphaFold", af_labels, af_seqs)]:
    seq_to_labels = defaultdict(list)
    for lab, s in zip(labels, seqs):
        seq_to_labels[s].append(lab)
    dup_groups = [labs for labs in seq_to_labels.values() if len(labs) > 1]
    print(f"\n{title}: n={len(seqs)} | unique={len(seq_to_labels)}")
    if dup_groups:
        print(f"{title}: duplicated sequences detected (inflate identity):")
        for g in sorted(dup_groups, key=len, reverse=True)[:10]:
            print("  -", ", ".join(g))
    else:
        print(f"{title}: no exact duplicate sequences detected")

# Summary stats (aligned-only)
_print_stats("Experimental aligned-only identity (%)", exp_id_df)
_print_stats("AlphaFold aligned-only identity (%)", af_id_df)

# More interpretable metrics: identity over max length + aligned coverage
exp_id_maxlen_df, exp_cov_df = identity_over_maxlen_and_coverage_matrix(exp_labels, exp_seqs)
af_id_maxlen_df, af_cov_df = identity_over_maxlen_and_coverage_matrix(af_labels, af_seqs)

_print_stats("Experimental identity over maxlen (%)", exp_id_maxlen_df)
_print_stats("AlphaFold identity over maxlen (%)", af_id_maxlen_df)
_print_stats("Experimental aligned coverage (%)", exp_cov_df)
_print_stats("AlphaFold aligned coverage (%)", af_cov_df)

# Alternative heatmaps (more interpretable than aligned-only identity)

exp_id_maxlen_df, exp_cov_df = identity_over_maxlen_and_coverage_matrix(exp_labels, exp_seqs)
af_id_maxlen_df, af_cov_df = identity_over_maxlen_and_coverage_matrix(af_labels, af_seqs)

def plot_heatmap(df: pd.DataFrame, title: str, out_path: Path, vmax: float) -> None:
    """Plot and save a labeled heatmap for a square matrix DataFrame."""
    fig, ax = plt.subplots(figsize=(6, 4))
    im = ax.imshow(df.values, vmin=0, vmax=vmax, cmap="viridis")
    ax.set_title(title)
    ax.set_xticks(range(len(df.columns)))
    ax.set_yticks(range(len(df.index)))
    ax.set_xticklabels(df.columns, rotation=90, fontsize=7)
    ax.set_yticklabels(df.index, fontsize=7)
    fig.colorbar(im, ax=ax, label=title.split("(")[-1].rstrip(")"))
    fig.tight_layout()
    fig.savefig(out_path, dpi=200)
    plt.show()
    print("Saved:", out_path)

# Identity heatmaps using matches/maxlen
plot_heatmap(
    exp_id_maxlen_df,
    "Pairwise Sequence Identity (Experimental; matches / maxlen)",
    FIGURES_DIR / "sequence_identity_heatmap_experimental_maxlen.png",
    vmax=50,
 )
plot_heatmap(
    af_id_maxlen_df,
    "Pairwise Sequence Identity (AlphaFold; matches / maxlen)",
    FIGURES_DIR / "sequence_identity_heatmap_alphafold_maxlen.png",
    vmax=50,
 )

# Coverage heatmaps (how much actually aligned)
plot_heatmap(
    exp_cov_df,
    "Aligned coverage (Experimental; aligned_pairs / maxlen)",
    FIGURES_DIR / "sequence_aligned_coverage_heatmap_experimental.png",
    vmax=100,
 )
plot_heatmap(
    af_cov_df,
    "Aligned coverage (AlphaFold; aligned_pairs / maxlen)",
    FIGURES_DIR / "sequence_aligned_coverage_heatmap_alphafold.png",
    vmax=100,
 )

"""<div style="text-align: center; font-size: 24px; font-weight: bold; border-top: 5px solid green; border-bottom: 2px solid green; padding: 10px;">
   5. Phase B (optional): Experimental vs AlphaFold sequence similarity
</div>

This adds a *per-position* similarity plot (aligned identity in a sliding window) between each experimental chain sequence and its AlphaFold model. This is useful to quickly see mismatches or missing coverage (gaps) after alignment.
"""

# Phase B extra: plot sequence similarity (experimental chain vs AlphaFold chain)

SEQSIM_DIR = FIGURES_DIR / "sequence_similarity"
SEQSIM_DIR.mkdir(parents=True, exist_ok=True)

def exp_vs_af_similarity_profile(exp_chain, af_chain, window: int = 15) -> pd.DataFrame:
    """Return a per-residue similarity profile on experimental residue numbering.

    Output columns:
    - exp_resseq, exp_aa
    - af_resseq, af_aa (NaN if gap)
    - is_aligned (bool)
    - is_match (bool/NaN)
    - rolling_identity_pct (float/NaN)
    """
    exp_seq, exp_res = chain_sequence_and_residues(exp_chain)
    af_seq, af_res = chain_sequence_and_residues(af_chain)

    pairs = align_index_pairs(exp_seq, af_seq)
    exp_to_af: Dict[int, int] = {i: j for i, j in pairs}

    rows: List[Dict] = []
    for exp_i, exp_r in enumerate(exp_res):
        exp_resseq = int(exp_r.id[1])
        exp_aa = seq1(exp_r.get_resname())
        if exp_i in exp_to_af:
            af_i = exp_to_af[exp_i]
            af_r = af_res[af_i]
            af_resseq = int(af_r.id[1])
            af_aa = seq1(af_r.get_resname())
            is_match = bool(exp_aa == af_aa)
            rows.append({
                "exp_resseq": exp_resseq,
                "exp_aa": exp_aa,
                "af_resseq": af_resseq,
                "af_aa": af_aa,
                "is_aligned": True,
                "is_match": is_match,
            })
        else:
            rows.append({
                "exp_resseq": exp_resseq,
                "exp_aa": exp_aa,
                "af_resseq": np.nan,
                "af_aa": "-",
                "is_aligned": False,
                "is_match": np.nan,
            })

    df = pd.DataFrame(rows)
    df["rolling_identity_pct"] = (
        df["is_match"].astype(float)
        .rolling(window=window, center=True, min_periods=max(3, window // 3))
        .mean()
        * 100.0
    )
    return df

seqsim_summary_rows: List[Dict] = []
for _, row in phaseA_df.iterrows():
    pdb_id = row["pdb_id"]
    chain_id = row["chain_id"]
    uniprot_id = row["uniprot_id"]

    exp_struct = parse_structure(Path(row["exp_file"]), f"EXP_{pdb_id}")
    af_struct = parse_structure(Path(row["af_file"]), f"AF_{uniprot_id}")

    exp_chain = get_chain(exp_struct, chain_id)
    af_chain = get_chain(af_struct, "A")

    prof = exp_vs_af_similarity_profile(exp_chain, af_chain, window=15)

    out_csv = RESULTS_DIR / f"sequence_similarity_{pdb_id}_{chain_id}_{uniprot_id}.csv"
    prof.to_csv(out_csv, index=False)

    fig, ax = plt.subplots(figsize=(7.5, 3))
    ax.plot(prof["exp_resseq"], prof["rolling_identity_pct"], lw=1.5, color="slateblue", label="Rolling identity (%)")

    gaps = prof[~prof["is_aligned"]]
    if len(gaps) > 0:
        ax.scatter(gaps["exp_resseq"], [2.0] * len(gaps), s=6, color="gray", alpha=0.6, label="Unaligned (gap)")

    ax.set_ylim(0, 105)
    ax.set_xlabel("Experimental residue number")
    ax.set_ylabel("% identity (windowed)")
    ax.set_title(f"Seq similarity: {pdb_id}:{chain_id} vs AF:{uniprot_id}")
    ax.grid(True, alpha=0.25)
    ax.legend(loc="lower left", fontsize=8)
    fig.tight_layout()

    out_png = SEQSIM_DIR / f"seqsim_{pdb_id}_{chain_id}_{uniprot_id}.png"
    fig.savefig(out_png)
    plt.close(fig)

    aligned_fraction = float(prof["is_aligned"].mean())
    mean_identity = float(np.nanmean(prof["is_match"].astype(float)) * 100.0)
    seqsim_summary_rows.append({
        "pdb_id": pdb_id,
        "chain_id": chain_id,
        "uniprot_id": uniprot_id,
        "aligned_fraction": aligned_fraction,
        "mean_identity_aligned_pct": mean_identity,
        "profile_csv": str(out_csv),
        "plot_png": str(out_png),
    })
    print(f"SeqSim done: {pdb_id}:{chain_id} | aligned={aligned_fraction*100:.1f}% | identity={mean_identity:.1f}%")

seqsim_df = pd.DataFrame(seqsim_summary_rows)
seqsim_df.to_csv(RESULTS_DIR / "phaseB_sequence_similarity_summary.csv", index=False)
display(seqsim_df)
print("Saved:")
print("-", RESULTS_DIR / "phaseB_sequence_similarity_summary.csv")
print("-", SEQSIM_DIR)

"""<div style="text-align: center; font-size: 24px; font-weight: bold; border-top: 5px solid green; border-bottom: 2px solid green; padding: 10px;">
   6. Phase C: Structural Analysis
</div>

Superimposition: Rotate and translate structures to minimize distance between Alpha-carbons (CA). <br>
RMSD: Calculate the quantitative difference in Ångströms. <br>
Contact Maps: Create a matrix where cell (i, j) is the distance between residue i and residue j. This creates a "fingerprint" of the fold.
"""

# Phase C: Structural analysis (superposition + per-residue deviation)

LOCAL_RMSD_DIR = FIGURES_DIR / "local_rmsd"
LOCAL_RMSD_DIR.mkdir(parents=True, exist_ok=True)

phaseC_summary_rows = []

for _, row in phaseA_df.iterrows():
    pdb_id = row["pdb_id"]
    chain_id = row["chain_id"]
    uniprot_id = row["uniprot_id"]

    exp_struct = parse_structure(Path(row["exp_file"]), f"EXP_{pdb_id}")
    af_struct = parse_structure(Path(row["af_file"]), f"AF_{uniprot_id}")

    exp_chain = get_chain(exp_struct, chain_id)
    af_chain = get_chain(af_struct, "A")

    global_rmsd_A, per_res_records = superpose_on_ca(exp_chain, af_chain)
    per_res_df = pd.DataFrame(per_res_records)
    per_res_df.insert(0, "pdb_id", pdb_id)
    per_res_df.insert(1, "chain_id", chain_id)
    per_res_df.insert(2, "uniprot_id", uniprot_id)

    out_csv = RESULTS_DIR / f"local_deviation_{pdb_id}_{chain_id}_{uniprot_id}.csv"
    per_res_df.to_csv(out_csv, index=False)

    # simple plot: CA distance vs residue index (experimental numbering)
    fig, ax = plt.subplots(figsize=(7, 3))
    ax.plot(per_res_df["exp_resseq"], per_res_df["ca_distance_A"], lw=1)
    ax.axhline(2.0, color="tomato", ls="--", lw=1, label="2Å")
    ax.set_title(f"{pdb_id}:{chain_id} vs AF:{uniprot_id} (global RMSD={global_rmsd_A:.2f}Å)")
    ax.set_xlabel("Experimental residue number")
    ax.set_ylabel("CA distance after superposition (Å)")
    ax.legend(loc="upper right")
    fig.tight_layout()
    out_png = LOCAL_RMSD_DIR / f"local_deviation_{pdb_id}_{chain_id}_{uniprot_id}.png"
    fig.savefig(out_png)
    plt.close(fig)

    # summarize "bad" regions: count residues above thresholds
    frac_gt2 = float((per_res_df["ca_distance_A"] > 2.0).mean())
    frac_gt4 = float((per_res_df["ca_distance_A"] > 4.0).mean())
    phaseC_summary_rows.append(
        {
            "pdb_id": pdb_id,
            "chain_id": chain_id,
            "uniprot_id": uniprot_id,
            "global_rmsd_A": global_rmsd_A,
            "n_aligned": int(len(per_res_df)),
            "frac_ca_gt2A": frac_gt2,
            "frac_ca_gt4A": frac_gt4,
            "per_residue_csv": str(out_csv),
            "plot_png": str(out_png),
        }
    )
    print(f"Phase C done: {pdb_id}:{chain_id} (RMSD={global_rmsd_A:.2f}Å)")

phaseC_df = pd.DataFrame(phaseC_summary_rows)
phaseC_df.to_csv(RESULTS_DIR / "phaseC_summary.csv", index=False)
phaseC_df

# Phase C quick summary: which proteins look worst?
display(phaseC_df.sort_values(["frac_ca_gt4A", "global_rmsd_A"], ascending=False).head(10))

if len(phaseC_df) > 0:
    # Show the first plot image inline
    first_plot = Path(phaseC_df.iloc[0]["plot_png"])
    if first_plot.exists():
        img = plt.imread(first_plot)
        plt.figure(figsize=(7, 3))
        plt.imshow(img)
        plt.axis("off")
        plt.show()

"""<div style="text-align: center; font-size: 24px; font-weight: bold; border-top: 5px solid green; border-bottom: 2px solid green; padding: 10px;">
   7. Phase C (optional): Identify regions where AlphaFold fails
</div>

Your Phase C computes per-residue CA deviation after superposition. Here we automatically *call out contiguous “bad regions”* (e.g., flexible/disordered loops) where deviation exceeds a threshold, and write a clean table per protein.
"""

# Phase C extra: segment the "bad" regions from per-residue deviation

def find_bad_segments(
    per_res_df: pd.DataFrame, threshold_A: float = 4.0, min_len: int = 5
 ) -> pd.DataFrame:
    """Find contiguous segments where ca_distance_A >= threshold_A.

    Returns columns: start_resseq, end_resseq, length, mean_ca_A, max_ca_A
    """
    df = per_res_df[["exp_resseq", "ca_distance_A"]].sort_values("exp_resseq").reset_index(drop=True)
    bad = df["ca_distance_A"] >= float(threshold_A)

    segments: List[Dict] = []
    start_idx: int | None = None
    for i, is_bad in enumerate(bad.tolist()):
        if is_bad and start_idx is None:
            start_idx = i
        elif (not is_bad) and start_idx is not None:
            seg = df.iloc[start_idx:i]
            if len(seg) >= min_len:
                segments.append({
                    "start_resseq": int(seg["exp_resseq"].iloc[0]),
                    "end_resseq": int(seg["exp_resseq"].iloc[-1]),
                    "length": int(len(seg)),
                    "mean_ca_A": float(seg["ca_distance_A"].mean()),
                    "max_ca_A": float(seg["ca_distance_A"].max()),
                })
            start_idx = None

    # handle segment reaching end
    if start_idx is not None:
        seg = df.iloc[start_idx:]
        if len(seg) >= min_len:
            segments.append({
                "start_resseq": int(seg["exp_resseq"].iloc[0]),
                "end_resseq": int(seg["exp_resseq"].iloc[-1]),
                "length": int(len(seg)),
                "mean_ca_A": float(seg["ca_distance_A"].mean()),
                "max_ca_A": float(seg["ca_distance_A"].max()),
            })

    return pd.DataFrame(segments)


bad_regions_rows: List[Dict] = []

for _, row in phaseA_df.iterrows():
    pdb_id = row["pdb_id"]
    chain_id = row["chain_id"]
    uniprot_id = row["uniprot_id"]

    per_csv = RESULTS_DIR / f"local_deviation_{pdb_id}_{chain_id}_{uniprot_id}.csv"
    if not per_csv.exists():
        continue
    per_res_df = pd.read_csv(per_csv)

    seg2 = find_bad_segments(per_res_df, threshold_A=2.0, min_len=5)
    seg4 = find_bad_segments(per_res_df, threshold_A=4.0, min_len=3)

    # Save per-protein tables too
    out_seg_csv = RESULTS_DIR / f"bad_regions_{pdb_id}_{chain_id}_{uniprot_id}.csv"
    seg4_out = seg4.copy()
    seg4_out.insert(0, "pdb_id", pdb_id)
    seg4_out.insert(1, "chain_id", chain_id)
    seg4_out.insert(2, "uniprot_id", uniprot_id)
    seg4_out.to_csv(out_seg_csv, index=False)

    # Collect a compact summary for the whole dataset
    bad_regions_rows.append({
        "pdb_id": pdb_id,
        "chain_id": chain_id,
        "uniprot_id": uniprot_id,
        "n_segments_ge2A": int(len(seg2)),
        "n_segments_ge4A": int(len(seg4)),
        "worst_segment_max_A": float(seg4["max_ca_A"].max()) if len(seg4) else 0.0,
        "worst_segment_mean_A": float(seg4["mean_ca_A"].max()) if len(seg4) else 0.0,
        "bad_regions_csv": str(out_seg_csv),
    })

bad_regions_df = pd.DataFrame(bad_regions_rows)
bad_regions_df.to_csv(RESULTS_DIR / "phaseC_bad_regions_summary.csv", index=False)
display(bad_regions_df.sort_values(["n_segments_ge4A", "worst_segment_max_A"], ascending=False).head(10))
print("Saved:")
print("-", RESULTS_DIR / "phaseC_bad_regions_summary.csv")

# Phase C Extra: Contact Maps (Intra-protein distance matrices)
# --------------------------------------------------------------------------------
# This fulfills the requirement: "Create a matrix where cell (i, j) is the distance
# between residue i and residue j. This creates a 'fingerprint' of the fold."

CONTACT_MAPS_DIR = FIGURES_DIR / "contact_maps"
CONTACT_MAPS_DIR.mkdir(parents=True, exist_ok=True)

def get_contact_matrix(chain) -> np.ndarray:
    """Calculate the distance matrix between all CA atoms in a chain."""
    # Extract list of CA residues using your existing helper function
    _, residues = chain_sequence_and_residues(chain)

    n = len(residues)
    matrix = np.zeros((n, n))

    # Calculate pairwise distances
    # Note: Bio.PDB 'minus' operator on atoms returns distance
    for i in range(n):
        for j in range(n):
            dist = residues[i]["CA"] - residues[j]["CA"]
            matrix[i, j] = dist

    return matrix

def plot_and_save_contact_comparison(pdb_id, exp_matrix, af_matrix):
    """Plot Experimental vs AlphaFold contact maps side-by-side."""
    fig, axes = plt.subplots(1, 2, figsize=(10, 4.5))

    # Common max distance for color scaling (e.g., 25 Angstroms)
    vmax = 25.0

    # Plot Experimental
    im1 = axes[0].imshow(exp_matrix, cmap='viridis_r', origin='lower', vmin=0, vmax=vmax)
    axes[0].set_title(f"Experimental: {pdb_id}")
    axes[0].set_xlabel("Residue Index")
    axes[0].set_ylabel("Residue Index")

    # Plot AlphaFold
    im2 = axes[1].imshow(af_matrix, cmap='viridis_r', origin='lower', vmin=0, vmax=vmax)
    axes[1].set_title(f"AlphaFold Prediction")
    axes[1].set_xlabel("Residue Index")
    axes[1].set_yticklabels([]) # Hide Y ticks on the second plot for cleanliness

    # Add colorbar
    cbar = fig.colorbar(im2, ax=axes.ravel().tolist(), label="Distance (Å)")

    save_path = CONTACT_MAPS_DIR / f"{pdb_id}_contact_map.png"
    plt.savefig(save_path, bbox_inches='tight')
    plt.close(fig) # Close to prevent printing 20 plots to the notebook output
    print(f"Saved contact map: {save_path.name}")

print(f"Generating contact maps for {len(phaseA_df)} proteins...")

for _, row in phaseA_df.iterrows():
    pdb_id = row["pdb_id"]
    # FIXED LINE BELOW: Changed 'chosen_chain' to 'chain_id'
    chain_id = row["chain_id"]
    uniprot_id = row["uniprot_id"]

    try:
        # 1. Parse Structures (using your existing paths and functions)
        exp_struct = parse_structure(Path(row["exp_file"]), f"EXP_{pdb_id}")
        af_struct = parse_structure(Path(row["af_file"]), f"AF_{uniprot_id}")

        # 2. Get Chains
        exp_chain = get_chain(exp_struct, chain_id)
        af_chain = get_chain(af_struct, "A") # AF models are always chain A

        # 3. Compute Matrices
        exp_mat = get_contact_matrix(exp_chain)
        af_mat = get_contact_matrix(af_chain)

        # 4. Plot and Save
        plot_and_save_contact_comparison(pdb_id, exp_mat, af_mat)

    except Exception as e:
        print(f"Skipping {pdb_id} due to error: {e}")

print(f"\nDone! Maps saved to: {CONTACT_MAPS_DIR}")

"""<div style="text-align: center; font-size: 24px; font-weight: bold; border-top: 5px solid green; border-bottom: 2px solid green; padding: 10px;">
   8. Phase C (optional): PyMOL structure overlay images
</div>

This generates **two** PyMOL cartoon overlays per protein (experimental chain vs AlphaFold chain):
- **Plain overlay** (no highlighting), like `alignment_view.png`
- **Error overlay** (experimental chain colored by CA error, plus yellow sticks for high-error residues)

Both images are zoomed to tightly fit the structures and are written under `figures/pymol_overlays/`.
"""

ensure_package("py3Dmol")
import py3Dmol

# Phase C extra: py3Dmol interactive viewers for each experimental vs AlphaFold pair

# We no longer need PyMOL rendering knobs, but we keep the viewing dimensions
VIEWER_WIDTH = 600
VIEWER_HEIGHT = 400

# --- Error visualization knobs ---
ERROR_CAP_A = 8.0
HIGHLIGHT_THRESHOLD_A = 4.0
MIN_HIGHLIGHT_RES = 3

overlay_rows: List[Dict] = []

for _, row in phaseA_df.iterrows():
    pdb_id = row["pdb_id"]
    chain_id = row["chain_id"]
    uniprot_id = row["uniprot_id"]

    exp_file = Path(row["exp_file"])
    af_file = Path(row["af_file"])

    # Read the raw PDB text data to feed into py3Dmol
    with open(exp_file, "r") as f:
        exp_data = f.read()
    with open(af_file, "r") as f:
        af_data = f.read()

    print(f"--- Visualizing {pdb_id} (Chain {chain_id}) vs AlphaFold ({uniprot_id}) ---")

    # Initialize the py3Dmol viewer
    view = py3Dmol.view(width=VIEWER_WIDTH, height=VIEWER_HEIGHT)

    # Load Model 0: Experimental (Cyan)
    view.addModel(exp_data, "pdb")
    view.setStyle({'model': 0}, {'cartoon': {'color': 'cyan'}})

    # Load Model 1: AlphaFold (Magenta, slightly transparent)
    view.addModel(af_data, "pdb")
    view.setStyle({'model': 1}, {'cartoon': {'color': 'magenta', 'opacity': 0.8}})

    # --- Error-based highlighting ---
    # Because py3Dmol can't dynamically rewrite B-factors like PyMOL,
    # we select specific residues to highlight based on your CSV directly.
    per_csv = RESULTS_DIR / f"local_deviation_{pdb_id}_{chain_id}_{uniprot_id}.csv"

    if per_csv.exists():
        per_res_df = pd.read_csv(per_csv)
        if {"exp_resseq", "ca_distance_A"}.issubset(per_res_df.columns):

            # Find residues above the threshold
            bad_res = (
                per_res_df.loc[per_res_df["ca_distance_A"] >= float(HIGHLIGHT_THRESHOLD_A), "exp_resseq"]
                .dropna()
                .astype(int)
                .tolist()
            )

            if len(bad_res) >= int(MIN_HIGHLIGHT_RES):
                # Apply stick and sphere formatting to high-error residues on the experimental model
                for resi in bad_res:
                    view.addStyle(
                        {'model': 0, 'chain': chain_id, 'resi': str(resi)},
                        {'stick': {'colorscheme': 'yellowCarbon', 'radius': 0.2},
                         'sphere': {'color': 'yellow', 'radius': 0.4}}
                    )
        else:
            print(f"[WARN] {per_csv.name}: missing columns exp_resseq/ca_distance_A")
    else:
        print(f"[WARN] Phase C CSV not found: {per_csv}")

    # Zoom to fit everything and render the interactive widget in the Colab cell
    view.zoomTo()
    view.show()

    # We update the dataframe tracking (removing PNG paths since we display inline)
    overlay_rows.append({
        "pdb_id": pdb_id,
        "chain_id": chain_id,
        "uniprot_id": uniprot_id,
        "per_residue_csv": str(per_csv),
        "status": "py3Dmol_rendered"
    })

overlay_df = pd.DataFrame(overlay_rows)
overlay_df.to_csv(RESULTS_DIR / "phaseC_py3dmol_tracking.csv", index=False)
display(overlay_df.head())

"""<div style="text-align: center; font-size: 24px; font-weight: bold; border-top: 5px solid green; border-bottom: 2px solid green; padding: 10px;">
   9. Phase D (optional): Binding & Interaction
</div>

Define a cutoff distance (e.g., 4Å) to define an "interaction." <br>
Iterate through all atoms in the ligand and find protein atoms within that cutoff. <br>
Compare these interaction fingerprints across your dataset.

"""

# Phase D: Ligand contacts (simple cutoff method)

CONTACTS_DIR = FIGURES_DIR / "contacts"
CONTACTS_DIR.mkdir(parents=True, exist_ok=True)

def is_water_residue(res) -> bool:
    """Return True if a residue looks like crystallographic water."""
    return res.get_resname().upper() in {"HOH", "WAT", "H2O"}

def iter_ligand_residues(model):
    """Yield non-water hetero residues (possible ligands/ions)."""
    for chain in model.get_chains():
        for res in chain.get_residues():
            hetfield = str(res.id[0]).strip()
            if hetfield == "":
                continue  # standard protein residue
            if is_water_residue(res):
                continue
            yield chain.id, res

def ligand_contacts_for_chain(exp_structure, protein_chain_id: str, cutoff_A: float = 4.0) -> pd.DataFrame:
    """Compute ligand contacts for one protein chain using a distance cutoff."""
    model = next(exp_structure.get_models())
    protein_chain = model[protein_chain_id]

    protein_atoms = [a for a in protein_chain.get_atoms() if a.element != "H"]
    ns = NeighborSearch(protein_atoms)

    rows: List[Dict] = []
    for lig_chain_id, lig_res in iter_ligand_residues(model):
        lig_atoms = [a for a in lig_res.get_atoms() if a.element != "H"]
        for atom in lig_atoms:
            close_atoms = ns.search(atom.get_coord(), cutoff_A, level="A")
            for close_atom in close_atoms:
                close_res = close_atom.get_parent()
                rows.append(
                    {
                        "lig_chain": lig_chain_id,
                        "lig_resname": lig_res.get_resname(),
                        "lig_resseq": int(lig_res.id[1]),
                        "protein_chain": protein_chain_id,
                        "prot_resname": close_res.get_resname(),
                        "prot_resseq": int(close_res.id[1]),
                        "distance_A": float(np.linalg.norm(atom.get_coord() - close_atom.get_coord())),
                    }
                )
    if not rows:
        return pd.DataFrame(
            columns=["lig_chain", "lig_resname", "lig_resseq", "protein_chain", "prot_resname", "prot_resseq", "distance_A"]
        )
    return pd.DataFrame(rows)

phaseD_summary_rows = []
for _, row in phaseA_df.iterrows():
    pdb_id = row["pdb_id"]
    chain_id = row["chain_id"]
    uniprot_id = row["uniprot_id"]

    exp_struct = parse_structure(Path(row["exp_file"]), f"EXP_{pdb_id}")
    contacts_df = ligand_contacts_for_chain(exp_struct, chain_id, cutoff_A=4.0)

    out_csv = RESULTS_DIR / f"contacts_{pdb_id}_{chain_id}.csv"
    contacts_df.to_csv(out_csv, index=False)

    # summarize top contacting residues (by number of contacts)
    if len(contacts_df) > 0:
        top = (
            contacts_df.groupby(["prot_resseq", "prot_resname"])
            .size()
            .sort_values(ascending=False)
            .head(12)
        )
        fig, ax = plt.subplots(figsize=(7, 3))
        labels = [f"{r}:{n}" for (r, n) in top.index]
        ax.bar(range(len(top)), top.values)
        ax.set_xticks(range(len(top)))
        ax.set_xticklabels(labels, rotation=45, ha="right")
        ax.set_ylabel("# atom-atom contacts")
        ax.set_title(f"Top ligand-contact residues ({pdb_id}:{chain_id})")
        fig.tight_layout()
        out_png = CONTACTS_DIR / f"contacts_{pdb_id}_{chain_id}.png"
        fig.savefig(out_png)
        plt.close(fig)
        n_ligands = contacts_df[["lig_chain", "lig_resname", "lig_resseq"]].drop_duplicates().shape[0]
    else:
        out_png = ""
        n_ligands = 0

    phaseD_summary_rows.append(
        {
            "pdb_id": pdb_id,
            "chain_id": chain_id,
            "uniprot_id": uniprot_id,
            "n_contacts": int(len(contacts_df)),
            "n_ligands": int(n_ligands),
            "contacts_csv": str(out_csv),
            "plot_png": str(out_png),
        }
    )
    print(f"Phase D done: {pdb_id}:{chain_id} | ligands={n_ligands} | contacts={len(contacts_df)}")

phaseD_df = pd.DataFrame(phaseD_summary_rows)
phaseD_df.to_csv(RESULTS_DIR / "phaseD_summary.csv", index=False)
phaseD_df